name: Integration tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    uses: amandahla/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      chaos-enabled: false
      chaos-experiments: pod-delete
      chaos-app-label: app.kubernetes.io/name=indico
      zap-dast-enabled: true
      zap-auth-header: Host
      zap-auth-header-value: indico.local
      zap-target-port: 8080
