name: Integration tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    uses: amandahla/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      chaos-enabled: false
      chaos-experiments: pod-delete
      chaos-app-label: app.kubernetes.io/name=indico
      zap-dast-enabled: true
      zap-auth-header: Host
      zap-auth-header-value: indico.local
      zap-target-port: 8080
      zap-before-command: "curl -H \"Host: indico.local\" $ZAP_TARGET:8080/bootstrap --data-raw 'csrf_token=00000000-0000-0000-0000-000000000000&first_name=admin&last_name=admin&email=admin%40admin.com&username=admin&password=lunarlobster&confirm_password=lunarlobster&affiliation=Canonical'"
