name: Hook test

on:
  workflow_dispatch:

jobs:
  do-hook-test:
    name: hook-test
    runs-on: ubuntu-22.04
    steps:
      - name: step1
        uses: zaproxy/action-full-scan@v0.4.0
        with:
            target: 'https://www.zaproxy.org/'
            cmd_options: '--hook "tests/zap/hook.py"'
