name: Hook test

on:
  workflow_dispatch:

jobs:
  hook-test:
    uses: zaproxy/action-full-scan@v0.4.0
    with:
        target: 'https://www.zaproxy.org/'
        cmd_options: '--hook "tests/zap/testhook.py"'
